# How long should we wait till we restart the server (in ticks)
# Default: 1728000 (24 hours) | 20 ticks = 1 second
restart-timer: 1728000

# What command should we execute after the timer has ended?
# Default: reboot 300
restart-cmd: "reboot 300"
